### PR TITLE
Add kodi importer

### PR DESCRIPTION
**Pull request by glensc**
This adds my old commits to create kodi importer

- https://github.com/pld-linux/griffith/commits/auto/th/griffith-0.13-7/Kodi.py

### CODE REVIEW

**Comment by glensc** [comment]
these should be probably removed, as these are specific to my workflow:
* d468310 - use requests_cache if available
* 5d5af3e - import only "seen" movies

this could be provided by griffith itself:
* cf78dd5 - use requests to download files

**Comment by glensc** [comment]
@micjahn let me know what you think

**Comment by micjahn** [comment]
Thanks. I merged it "as-is". At the moment I don't have the time to review your code. I trust you that it works.

**Comment by glensc** [comment]
thanks, can improve if needed, now that upstream has new home!

**Pull request merged**
